name: test

on:
#  schedule:
#  - cron: '2 0 * * * *'
#
  push:
    branches:
    - workflows



jobs:
 build:
    name: test
    runs-on: windows-latest

    env:
      TEMP: c:\temp
      BUILDBASE: c:\temp

    steps:
    - name: override
      run: |
       set
       mkdir %MYWORKSPACE%
       echo "GITHUB_WORKSPACE=c:/workspace/" >> %GITHUB_ENV%

    - name: changed?
      run: set

# vim: set nowrap :
