name: test

on:
#  schedule:
#  - cron: '2 0 * * * *'
#
  push:
    branches:
    - workflows



jobs:
 build:
    name: test
    runs-on: windows-latest

    env:
      TEMP: c:\temp
      BUILDBASE: c:\temp

    steps:
    - name: override
      shell: cmd
      run: |
       echo CD:%CD%
       mkdir %MYWORKSPACE%
       echo GITHUB_WORKSPACE=%GITHUB_WORKSPACE%
       dir %GITHUB_ENV%
       echo "GITHUB_WORKSPACE=c:/workspace/" >> %GITHUB_ENV%
       dir c:
       dir d:

    - name: changed?
      shell: cmd
      run: echo GITHUB_WORKSPACE=

# vim: set nowrap :
