name: test

on:
#  schedule:
#  - cron: '2 0 * * * *'
#
  push:
    branches:
    - workflows



jobs:
 build:
    name: test
    runs-on: windows-latest

    env:
      BASE: c:\w

    steps:
    - name: use workspace on C
      shell: cmd
      run: |
       echo on
       cd \
       mkdir %BASE%
       rd %GITHUB_WORKSPACE%
       cmd /c mklink /j %GITHUB_WORKSPACE% %BASE%
       echo >%GITHUB_WORKSPACE%\foo.txt
       if not exist %BASE%\foo.txt (echo junction not active & exit /b 1)

    - name: Working
      shell: cmd
      run: |
        dir /s /b %GITHUB_WORKSPACE% %BASE%

# vim: set nowrap :
