name: test

on:
#  schedule:
#  - cron: '2 0 * * * *'
#
  push:
    branches:
    - workflows



jobs:
 build:
    name: test
    runs-on: windows-latest

    env:
      TEMP: c:\t
      BASE: c:\a

    steps:
    - name: override
      shell: cmd
      run: |
       echo CD:%CD%
       echo GITHUB_WORKSPACE=%GITHUB_WORKSPACE%
       dir %GITHUB_ENV%
       mkdir %BUILDBASE%
       echo "GITHUB_WORKSPACE=%BUILDBASE%" >> %GITHUB_ENV%
       dir c:
       dir d:

    - name: changed?
      shell: cmd
      run: echo GITHUB_WORKSPACE=%GITHUB_WORKSPACE%

# vim: set nowrap :
