name: test

on:
#  schedule:
#  - cron: '2 0 * * * *'
#
  push:
    branches:
    - workflows



jobs:
 build:
    name: test
    runs-on: windows-latest

    env:
      TEMP: c:\temp
      BUILDBASE: c:\temp

    steps:
    - run: set
    - run: mkdir %MYWORKSPACE%
    - run: echo "GITHUB_WORKSPACE=c:/workspace/" >> %GITHUB_ENV%
    - run: set

# vim: set nowrap :
