name: test

on:
#  schedule:
#  - cron: '2 0 * * * *'
#
  push:
    branches:
    - workflows



jobs:
 build:
    name: test
    runs-on: windows-latest

    env:
      BASE: c:\workspace

    steps:
    - name: override
      shell: cmd
      run: |
       echo on
       dir c: d:
       echo TEMP:%TEMP%
       echo BASE:%TEMP%
       mkdir %BASE%
       dir /s /b %GITHUB_WORKSPACE%
       echo CD:%CD%
       dir %GITHUB_ENV%
       rd %GITHUB_WORKSPACE%
       if not exist %GITHUB_WORKSPACE% echo REMOVED
       cmd /c mklink /j %GITHUB_WORKSPACE% %BASE%
       if exist %GITHUB_WORKSPACE% ( echo junction exists ) else ( echo junction missing )
       dir %GITHUB_WORKSPACE% 

    - name: changed?
      shell: cmd
      run: |
        echo GITHUB_WORKSPACE=%GITHUB_WORKSPACE%
        dir /s /b %GITHUB_WORKSPACE%
        dir /s /b %BASE%

# vim: set nowrap :
